# Generated by Django 5.2 on 2025-06-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taberna', '0002_alter_user_options_alter_user_apellido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='apellido',
            field=models.CharField(blank=True, max_length=150, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, verbose_name='nombre'),
        ),
    ]
