# Generated by Django 5.2 on 2025-06-13 00:53

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taberna', '0003_alter_user_options_alter_user_apellido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Producto del menú', 'verbose_name_plural': 'Productos del menú'},
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('comida', 'Comida'), ('bebida', 'Bebida'), ('postre', 'Postre')], default='comida', max_length=50, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Ingredientes, preparación, maridaje...', verbose_name='Descripción detallada'),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_destacado',
            field=models.BooleanField(default=False, verbose_name='¿Producto destacado?'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación en el menú'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Foto del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(help_text='Ej: Cerveza Artesanal, Asado de Tira', max_length=100, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio ($)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Unidades disponibles'),
        ),
    ]
