# Generated by Django 5.2 on 2025-06-13 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taberna', '0003_contacto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacto',
            new_name='Comentario',
        ),
    ]
