# Generated by Django 5.2 on 2025-06-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taberna', '0004_rename_contacto_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientefrecuente',
            name='estado',
            field=models.CharField(choices=[('A', 'Avistado'), ('D', 'Desaparecido')], default='A', max_length=1, verbose_name='Estado del cliente'),
        ),
    ]
