# Generated by Django 5.2 on 2025-06-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taberna', '0005_clientefrecuente_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabernero',
            name='descripcion',
            field=models.TextField(default='Tabernero experimentado en la cocina y el servicio al cliente.', verbose_name='Descripción del tabernero'),
        ),
    ]
