# Generated by Django 5.2 on 2025-06-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taberna', '0006_tabernero_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientefrecuente',
            name='descripcion',
            field=models.TextField(default='Cliente frecuente que disfruta de nuestros platos y bebidas.', verbose_name='Descripción del cliente'),
        ),
    ]
