# Generated by Django 5.2 on 2025-06-13 17:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taberna', '0007_clientefrecuente_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción detallada'),
        ),
    ]
